[phases.setup]
nixPkgs = ["php81", "php81Packages.composer"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader"]

[phases.build]
cmds = ["echo 'Build phase completed'"]

[start]
cmd = "php -d upload_max_filesize=20M -d post_max_size=20M -d max_execution_time=300 -d memory_limit=256M -S 0.0.0.0:$PORT -t ."
